# Generated by Django 4.2 on 2023-05-25 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nacionalidad', models.CharField(max_length=200)),
                ('añoNacimiento', models.DateField(null=True)),
                ('resumen', models.CharField(max_length=300)),
                ('foto', models.ImageField(upload_to='images/actor')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nacionalidad', models.CharField(max_length=200)),
                ('añoNacimiento', models.DateField(null=True)),
                ('resumen', models.CharField(max_length=300)),
                ('foto', models.ImageField(upload_to='images/director')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('añoRealizacion', models.DateField(null=True)),
                ('resumen', models.TextField()),
                ('foto', models.ImageField(upload_to='images/pelicula')),
                ('categoria', models.CharField(max_length=200)),
                ('ranking', models.DecimalField(decimal_places=1, max_digits=2)),
                ('actores', models.ManyToManyField(to='peliculas.actor')),
                ('directores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.director')),
            ],
        ),
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('reseña', models.TextField()),
                ('puntaje', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('peli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.pelicula')),
            ],
        ),
    ]
