# Generated by Django 4.2 on 2023-05-25 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_alter_pelicula_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='peli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criticas', to='peliculas.pelicula'),
        ),
    ]
