# Generated by Django 4.2 on 2023-06-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_remove_pelicula_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='ranking',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
