# Generated by Django 4.2 on 2023-06-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_pelicula_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='categoria',
            field=models.CharField(choices=[('Acción', 'Acción'), ('Aventura', 'Aventura'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Comedia', 'Comedia'), ('No-Ficción/Documental', 'No-Ficción/Documental'), ('Drama', 'Drama'), ('Fantasía', 'Fantasía'), ('Musical', 'Musical')], default='', max_length=200),
        ),
    ]
