# Generated by Django 4.2 on 2023-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0010_alter_actor_foto_alter_director_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='critica',
            name='estado',
            field=models.CharField(choices=[('inicio', 'inicio'), ('aprobado', 'aprobado'), ('desaprobado', 'desaprobado')], default='inicio', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='critica',
            name='reseña',
            field=models.TextField(verbose_name='comentario'),
        ),
    ]
