# Generated by Django 4.2 on 2023-07-21 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0011_critica_estado_alter_critica_reseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='critica',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
    ]
